os: linux
sudo: false
language: python

python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python run.py
cache:
  - pip
branches:
  only:
    - master

notifications:
  email: false